name: pokemmo
title: PokeMMO
base: core20
version: '1.1d'
summary: PokeMMO Game Client
license: 'Proprietary'
description: |
  PokeMMO is an online-only emulator for several popular Nintendo DS & Game Boy Advance games,
  allowing you to play, talk, fight, and trade with other players in realtime across multiple
  platforms.

  This game requires a constant internet connection. Usage of this program requires an account
  with https://pokemmo.eu/ and requires you to accept the PokeMMO Terms of Service at login

grade: stable
confinement: strict

architectures:
  - build-on: arm64
  - build-on: armhf
  - build-on: amd64

package-repositories:
  - type: apt
    components: [main]
    suites: [stable]
    key-id: 99A5C88E3C5B1FA8B05A19D332E9750179FCEA62
    url: https://apt.bell-sw.com/

apps:
  pokemmo:
    command: java -jar $SNAP/jar/unix-installer.jar
    extensions: [gnome-3-38]
    plugs:
      - network
      - opengl
      - home
      - joystick
      - audio-playback
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7
    environment:
      JAVA_HOME: "$SNAP/usr/lib/jvm/bellsoft-java11-runtime-$SNAPCRAFT_TARGET_ARCH"
      _JAVA_OPTIONS: -Dfile.encoding="UTF-8"
      XDG_DATA_HOME: "$SNAP/usr/share"
      XDG_CONFIG_HOME: "$XDG_DATA_HOME/.config"
      PATH: "$JAVA_HOME/bin/:$PATH"
      DISPLAY: "$DISPLAY"
parts:
  gradle:
    plugin: nil
    override-pull: |
      curl --connect-timeout 5 --retry 5 -L https://services.gradle.org/distributions/gradle-7.3.1-bin.zip -o gradle-7.3.1-bin.zip && mv $SNAPCRAFT_PART_SRC/gradle-7.3.1-bin.zip $SNAPCRAFT_STAGE
    build-packages:
      - curl
  pokemmo:
    after: [gradle]
    plugin: dump
    source: https://github.com/kyu-n/pokemmo-unix-installer.git
    source-type: git
    override-pull: |
      snapcraftctl pull && cp $SNAPCRAFT_STAGE/gradle-7.3.1-bin.zip $SNAPCRAFT_PART_SRC/gradle/wrapper/gradle-7.3.1-bin.zip
    # I have no idea why the && is necessary, but override-build will terminate prematurely unless we chain commands after gradlew
    override-build: |
      set -x
      ./gradlew distJar && mkdir $SNAPCRAFT_PART_INSTALL/jar && cp build/libs/unix-installer.jar $SNAPCRAFT_PART_INSTALL/jar/unix-installer.jar && \
      case "$SNAPCRAFT_TARGET_ARCH" in
        amd64) ln -s usr/lib/jvm/bellsoft-java11-runtime-amd64/bin/java $SNAPCRAFT_PRIME/java ;;
        arm64) ln -s usr/lib/jvm/bellsoft-java11-runtime-aarch64/bin/java $SNAPCRAFT_PRIME/java ;;
        armhf) ln -s usr/lib/jvm/bellsoft-java11-runtime-arm32-vfp-hflt/bin/java $SNAPCRAFT_PRIME/java ;;
      esac
    stage-packages:
      - libglu1-mesa
      - zenity
      - x11-utils
      - bellsoft-java11-runtime
    build-packages:
      - bellsoft-java11