name: pokemmo
title: PokeMMO
base: core20
version: '1.1a'
summary: PokeMMO Game Client
license: 'Proprietary'
description: |
  PokeMMO is an online-only emulator for several popular Nintendo DS & Game Boy Advance games,
  allowing you to play, talk, fight, and trade with other players in realtime across multiple
  platforms.

  This game requires a constant internet connection. Usage of this program requires an account
  with https://pokemmo.eu/ and requires you to accept the PokeMMO Terms of Service at login

grade: devel
confinement: strict
architectures:
  - build-on: arm64
  - build-on: armhf
  - build-on: amd64

package-repositories:
  - type: apt
    components: [main]
    suites: [stable]
    key-id: 99A5C88E3C5B1FA8B05A19D332E9750179FCEA62
    url: https://apt.bell-sw.com/

apps:
  pokemmo:
    command: usr/lib/jvm/bellsoft-java11-runtime-$SNAPCRAFT_TARGET_ARCH/bin/java -jar $SNAP/jar/unix-installer.jar
    extensions: [gnome-3-38]
    plugs:
      - network
      - opengl
      - home
      - joystick
      - audio-playback
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7
      - hardware-observe
      - system-observe
    environment:
      JAVA_HOME: "$SNAP/usr/lib/jvm/bellsoft-java11-runtime-$SNAPCRAFT_TARGET_ARCH"
      _JAVA_OPTIONS: -Dfile.encoding="UTF-8"
      XDG_DATA_HOME: "$SNAP/usr/share"
      XDG_CONFIG_HOME: "$XDG_DATA_HOME/.config"
      PATH: "$JAVA_HOME/bin/:$PATH"
parts:
  pokemmo:
    plugin: dump
    source: https://github.com/kyu-n/pokemmo-unix-installer.git
    source-type: git
    # For some reason, this stage will terminate prematurely unless the commands are chained..?
    override-build: |
      ./gradlew distJar && mkdir $SNAPCRAFT_PART_INSTALL/jar && cp build/libs/unix-installer.jar $SNAPCRAFT_PART_INSTALL/jar/unix-installer.jar
    stage-packages:
      - libglu1-mesa
      - bellsoft-java11-runtime
    build-packages:
      - bellsoft-java11